name: Build and Deployment

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: |
          echo "@iam-hussain:registry=https://npm.pkg.github.com" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc
      - run: npm ci
      - run: npm run prisma:generate
      - run: npm run build
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

  deployment:
    name: Deployment
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Connect SSH and Run Scripts
        env:
          TOKEN: ${{ secrets.TOKEN }}
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd /root/projects/qd-service
            nvm use
            git checkout .
            git pull
            npm i
            npm run prisma:setup
            npm run build
            pm2 restart qd-service
